#!/bin/sh

. ./hib-utils.sh

exec 4<&0

prompt () {
	read -p "$1" junk <&4 || exit 1
}

process_group () {
	path="$1"
	shift
	for tor in "$@" ; do
		# get torrents
		eval $tor
		found=$(transmission-remote -l | grep "$out")
		if [ -z "$found" ] ; then
			echo "$out not being downloaded yet. Adding $tor ..."
			transmission-remote -w "$path"
			transmission-remote -a $tor
			echo "\tdone."
			prompt "Press enter to continue"
			continue
		fi
		tornum="$(echo $found | cut -f1 -d\ )"
		tornum="${tornum%\*}"
		dpath="$(transmission-remote -t $tornum -i | grep Location: | cut -c13-)"
		# remove optional final /
		dpath="${dpath%/}"
		if [ "$dpath" = "$path" ] ; then
			echo "torrent $tornum ($out) set to correct path $path"
			if [ -e "$path/$out" ] ; then
				echo "\tand $out exists"
			else
				echo "\tbut $out does not exist; restarting torrent"
				transmission-remote -t $tornum --start
			fi
			continue
		fi
		echo "$out is torrent $tornum,"
		echo "\tplaced in $dpath,"
		echo "\tshould be $path,"
		echo "\tmoving ..."
		prompt "^C to BREAK, [Enter] to proceed"
		transmission-remote -t $tornum --start
		transmission-remote -t $tornum --move $path
		echo "\tdone."
		prompt "[Enter] to continue"
	done
}

awk '{if (sub(/\\$/,"")) printf "%s", $0; else print $0}' doit | grep add_torrent | while read add qpath tors ; do
	# unquote path:
	eval path=$qpath
	# remove optional final /
	path="${path%/}"
	eval process_group "$path" $tors
done
